permissions_granted_over_SA:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2024-09-24T13:59:54.928287Z'
  enabled: true
  id: ru_b8ae3a1d-287e-4d72-9bd4-5788f95cf6e8
  resource_name: projects/112611561358/locations/us/instances/960a2f65-4940-4cc4-b6c2-ca605f9a2a4c/rules/ru_b8ae3a1d-287e-4d72-9bd4-5788f95cf6e8
  revision_create_time: '2024-09-24T13:59:54.928287Z'
  revision_id: v_1727186394_928287000
  run_frequency: LIVE
  type: SINGLE_EVENT
firewall_rules_modified_or_deleted:
  alerting: true
  enabled: true
gcp_admin_privileged_roles_added_to_service_accounts:
  alerting: true
  enabled: true
