#initial workflow
name: SecOps sync detection rules
on:
  pull_request:
    branches:
      - main
jobs:
  pull-existing-detections:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting rule sync from SecOps instance..."
