#initial workflow
name: SecOps sync detection rules
on:
  pull_request:
    branches:
      - main
jobs:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Starting rule sync from SecOps instance..."
