#initial workflow
name: SecOps sync detection rules
on:
  workflow_dispatch:
jobs:
  pull-existing-detections:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: 
      image: python:3.10-slim
    steps:
      #changing ownership of python cache
      - run: sudo chown -R $(whoami) /github/home
      - run: echo "Starting rule sync from SecOps instance..."
      - run: echo "Setting up Python environment."
      - run: pip install --upgrade pip
      - run: pip install virtualenv
      - run: python -m virtualenv venv
      - run: source venv/bin/activate
      - run: which python  # Check that the virtual environment is activated.
      - run: python --version ; pip --version
      # Install project requirements.
      - run: pip install -r requirements_dev.txt

      # Setting up git environment.
      - run: echo "Installing git."
      - run: apt-get update -qy && apt-get upgrade -qy
      - run: apt-get install -y git
      - run: git --version
