name: Test workflow
on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environmen
        default: default

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      - run: echo "This is var $KAKA"
        env:
          KAKA: ${{ vars.CI_COMMIT_SHA }}
